//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSTransferManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BITSTransferManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} MB.
        /// </summary>
        internal static string FileProgressByteCount {
            get {
                return ResourceManager.GetString("FileProgressByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} MB.
        /// </summary>
        internal static string FileProgressByteCountUnknown {
            get {
                return ResourceManager.GetString("FileProgressByteCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string JobCostAlways {
            get {
                return ResourceManager.GetString("JobCostAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No surcharge.
        /// </summary>
        internal static string JobCostNoSurcharge {
            get {
                return ResourceManager.GetString("JobCostNoSurcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string JobCostNotAvailable {
            get {
                return ResourceManager.GetString("JobCostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not roaming.
        /// </summary>
        internal static string JobCostNotRoaming {
            get {
                return ResourceManager.GetString("JobCostNotRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string JobCostStandard {
            get {
                return ResourceManager.GetString("JobCostStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrestricted.
        /// </summary>
        internal static string JobCostUnrestricted {
            get {
                return ResourceManager.GetString("JobCostUnrestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority	.
        /// </summary>
        internal static string JobPriority {
            get {
                return ResourceManager.GetString("JobPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string JobPriorityForeground {
            get {
                return ResourceManager.GetString("JobPriorityForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string JobPriorityHigh {
            get {
                return ResourceManager.GetString("JobPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string JobPriorityLow {
            get {
                return ResourceManager.GetString("JobPriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string JobPriorityNormal {
            get {
                return ResourceManager.GetString("JobPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job State.
        /// </summary>
        internal static string JobState {
            get {
                return ResourceManager.GetString("JobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        internal static string JobStateAcknowledged {
            get {
                return ResourceManager.GetString("JobStateAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string JobStateCancelled {
            get {
                return ResourceManager.GetString("JobStateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string JobStateConnecting {
            get {
                return ResourceManager.GetString("JobStateConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string JobStateError {
            get {
                return ResourceManager.GetString("JobStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😎.
        /// </summary>
        internal static string JobStateIconAcknowledged {
            get {
                return ResourceManager.GetString("JobStateIconAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😧.
        /// </summary>
        internal static string JobStateIconCancelled {
            get {
                return ResourceManager.GetString("JobStateIconCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😵.
        /// </summary>
        internal static string JobStateIconConnecting {
            get {
                return ResourceManager.GetString("JobStateIconConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😡.
        /// </summary>
        internal static string JobStateIconError {
            get {
                return ResourceManager.GetString("JobStateIconError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙂.
        /// </summary>
        internal static string JobStateIconQueued {
            get {
                return ResourceManager.GetString("JobStateIconQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😴.
        /// </summary>
        internal static string JobStateIconSuspended {
            get {
                return ResourceManager.GetString("JobStateIconSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😁.
        /// </summary>
        internal static string JobStateIconTransferred {
            get {
                return ResourceManager.GetString("JobStateIconTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😏.
        /// </summary>
        internal static string JobStateIconTransferring {
            get {
                return ResourceManager.GetString("JobStateIconTransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😬.
        /// </summary>
        internal static string JobStateIconTransientError {
            get {
                return ResourceManager.GetString("JobStateIconTransientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string JobStateQueued {
            get {
                return ResourceManager.GetString("JobStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string JobStateSuspended {
            get {
                return ResourceManager.GetString("JobStateSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        internal static string JobStateTransferred {
            get {
                return ResourceManager.GetString("JobStateTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring.
        /// </summary>
        internal static string JobStateTransferring {
            get {
                return ResourceManager.GetString("JobStateTransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient Error.
        /// </summary>
        internal static string JobStateTransientError {
            get {
                return ResourceManager.GetString("JobStateTransientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job State Unknown ({0}).
        /// </summary>
        internal static string JobStateUnknown {
            get {
                return ResourceManager.GetString("JobStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        internal static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string JobTypeDownload {
            get {
                return ResourceManager.GetString("JobTypeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string JobTypeUpload {
            get {
                return ResourceManager.GetString("JobTypeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Reply.
        /// </summary>
        internal static string JobTypeUploadReply {
            get {
                return ResourceManager.GetString("JobTypeUploadReply", resourceCulture);
            }
        }
    }
}
